import type { Metadata } from 'next'
import Providers from '../providers'
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { Poppins } from 'next/font/google'

const poppins = Poppins({ weight: ['400'], subsets: ['latin-ext'] });

export const metadata: Metadata = {
    title: 'Travelnik - Dashboard',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        locale: string;
    };
}

export default async function RootLayout({ children }: RootLayoutProps) {
    return (
        <html className={poppins.className}>
            <body>
                <Providers>
                    <Toaster position="top-right" />
                    {children}
                </Providers>
            </body>
        </html>
    )
}
