import type { Metadata } from 'next'
import './globals.css'
import Providers from './providers'
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { Poppins } from 'next/font/google'

const poppins = Poppins({ weight: ['400'], subsets: ['latin-ext'] });

export const metadata: Metadata = {
  title: 'Travelnik - Explore Travnik in few clicks',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default async function RootLayout({ children, params: { locale } }: RootLayoutProps) {


  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} className={poppins.className}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <Toaster position="top-right" />
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
